/** French is the studio language. Operators work in French. */

export const studio = {
  nav: {
    floor: "Salle",
    archive: "Archives",
    portraits: "Portraits",
    out: "Sortir",
  },
  auth: {
    loginFail: "Mauvais email ou mot de passe",
    registerFail: "Impossible d’ouvrir le booth",
    email: "Email",
    password: "Mot de passe",
    passwordNew: "Mot de passe · 8+",
  },
  floor: {
    house: "Maison",
    yourBooths: "Vos booths",
    lead: "Habillez un booth pour un gala, un forum, une salle XR, une nuit à N’Djamena. Ouvrez le kiosk sur l’ordinateur. Les invités tapent là.",
    demo: "Wan attend une clé Singapour. Les clichés s’impriment quand même.",
    newBooth: "Nouveau booth",
    tonightName: "Le nom de ce soir",
    open: "Ouvrir",
    floor: "Salle",
    portraitsOpen: "Portraits ouverts",
    recorded: (n: number) => `${n} inscrits`,
    empty: "Vide",
    noBooth: "Pas encore de booth",
    emptyLead: "Nommez-en un à gauche. La salle reste sombre tant que vous n’en avez pas.",
    live: "Ouvert",
    dark: "Éteint",
    guestsPrints: (g: number, p: number) => `${g} invités · ${p} clichés`,
    dress: "Habiller",
    kiosk: "Kiosk",
    wall: "Mur",
    loadFail: "Impossible de charger les booths",
    createFail: "Impossible de créer le booth",
    defaultSubtitle: "Votre visage. Un autre lieu.",
  },
  dress: {
    studio: "Atelier",
    opening: "Ouverture du booth…",
    onFloor: "Sur le plateau",
    dark: "Éteint",
    untitled: "Booth sans nom",
    live: "Ouvert",
    darkBtn: "Éteint",
    saving: "Enregistrement…",
    saved: "Enregistré.",
    saveFail: "Impossible d’enregistrer",
    saveFrameFail: "Impossible d’enregistrer le cadre",
    autosave: "Enregistrement auto",
    openKiosk: "Ouvrir le kiosk",
    kiosk: "Kiosk",
    tabPrint: "Papier",
    tabLooks: "Lieux",
    tabNight: "Ce soir",
    tabsAria: "Atelier",
    proofAlt: "Épreuve",
    souvenirCaption: "Le souvenir que les invités gardent.",
    event: "Événement",
    screenSays: "Ce que dit l’écran",
    boothName: "Nom du booth",
    boothNamePh: "Booth principal",
    kioskLine: "Ligne du kiosk",
    kioskLinePh: "Votre visage. Un autre lieu.",
    paper: "Papier",
    thePrint: "Le cliché",
    paperLead:
      "Cinq feuilles, du plateau d’un festival, d’un gala, d’un sommet. Votre marque couvre la plaque — bord à bord, jamais un bijou au centre.",
    signature: "Signature",
    signaturePh: "Un nom, une maison, une ligne",
    optionalTitle: "Titre optionnel",
    optionalTitlePh: "Affiché seulement si vous ajoutez la ligne",
    markOnly: "Marque seule",
    addLine: "Ajouter la ligne",
    ink: "Encre",
    replaceLogo: "Remplacer le logo",
    uploadLogo: "Importer le logo",
    makingProof: "Épreuve en cours…",
    proofPrint: "Tirer une épreuve",
    proofFail: "Impossible de tirer une épreuve",
    looks: "Lieux & rôles — Tchad, atelier, XR, fête",
    guestsTap: "Ce que les invités peuvent toucher",
    looksCount: (n: number) =>
      n === 1
        ? "1 lieu sur le plateau. Les lots ajoutent — ils ne remplacent jamais."
        : `${n} lieux sur le plateau. Les lots ajoutent — ils ne remplacent jamais.`,
    looksNone: "Laissez tout vide : tous les lieux restent ouverts.",
    clear: "Vider",
    tonight: "Ce soir",
    ready: "Prêt pour les invités",
    print: "Cliché",
    looksLabel: "Lieux",
    liveLabel: "Ouvert",
    everyLook: "Tous les lieux ouverts",
    nLooks: (n: number) => (n === 1 ? "1 lieu" : `${n} lieux`),
    stillDark: "Encore éteint",
    laptopIsBooth: "L’ordinateur est le booth. Le téléphone est optionnel.",
    laptop: "Ordinateur",
    phone: "Téléphone",
    copyBooth: "Copier le lien du booth",
    copyLens: "Copier le lien de l’appareil",
    copyWall: "Copier le mur",
    openLens: "Ouvrir l’appareil",
    openWall: "Ouvrir le mur",
    playWall: "Lancer le mur",
    run: "Service",
    howNight: "Comment la soirée tourne",
    guestPicks: "L’invité choisit",
    wePick: "Nous choisissons",
    qrKeep: "QR + garder",
    askEmail: "Demander l’email",
    stillsOnly: "Photos seules",
    addFilm: "Ajouter le film",
    consent: "Ligne de consentement",
    consentPh: "Ligne optionnelle avant la caméra.",
  },
  archive: {
    eyebrow: "Archives",
    title: "Épreuves",
    lead: "Ouvrez-en une pour la garder.",
    all: "Tous",
    find: "Trouver un lieu",
    empty: "Pas encore d’invités.",
  },
  portraits: {
    eyebrow: "Portraits",
    title: "Les portraits sont ouverts",
    lead: "Pas de plafond pour l’instant. Une photo compte 1, le film +3 — rien n’est bloqué.",
    recorded: "Inscrits dans la maison",
    addPack: "Ajouter un lot · 25",
    addFail: "Impossible d’ajouter des portraits",
    added: "25 portraits ajoutés. Une photo compte 1. Le film sur le premier lieu, +3.",
  },
  look: {
    eyebrow: "Votre lieu",
    title: "Nommez-le. L’IA le construit.",
    lead: "Un anniversaire, un mariage, un forum — jeunesse, IA, Sahel. Ajoutez les noms et le sentiment.",
    namePh: (sample: string) => `Nom du lieu — ${sample}`,
    whoPh: (sample: string) => `Pour qui — ${sample}`,
    nameFail: "Nommez le lieu",
    buildFail: "Impossible de construire le lieu",
    done: (title: string) => `${title} est sur le plateau.`,
    accent: "Accent",
    building: "Construction…",
    build: "Construire ce lieu",
  },
  picker: {
    tap: "Touchez un portrait",
    find: "Trouver un portrait",
    remove: "Retirer",
    empty: "Aucun lieu ici.",
  },
  copyBtn: {
    link: "Copier le lien",
    copied: "Copié",
  },
  lost: {
    eyebrow: "Introuvable",
    title: "Ce booth est hors ligne.",
    en: "This booth is offline.",
    home: "Accueil",
    homeEn: "Home",
  },
  status: {
    queued: "En file",
    running: "En cours",
    failed: "Manqué",
    ready: "Prêt",
    retry: "Nouvelle tentative",
  },
} as const;

export function statusFr(status: string) {
  return studio.status[status as keyof typeof studio.status] || status;
}

/** User-facing API errors. French default. */
export const apiCopy = {
  invalidRequest: "Requête invalide",
  unexpected: "Erreur inattendue du serveur",
  badCredentials: "Mauvais email ou mot de passe",
  noWorkspace: "Aucun atelier sur ce compte",
  emailTaken: "Un compte existe déjà avec cet email",
  signIn: "Connexion requise",
  boothNotFound: "Photobooth introuvable",
  boothOffline: "Ce booth est hors ligne.",
  boothUnavailable: "Booth indisponible",
  photoRequired: "Une photo est requise",
  unknownStyle: "Lieu inconnu",
  pickTheme: "Touchez au moins un lieu.",
  lookExists: "Ce nom de lieu est déjà dans la maison",
  missingLook: "Lieu manquant",
  lookNotFound: "Lieu introuvable",
  sessionExpired: "Ce souvenir a expiré.",
  sessionNotFound: "Séance introuvable",
  galleryNotFound: "Mur introuvable",
  tooMany: "Trop de demandes. Réessayez dans un instant.",
  jpegOnly: "Seuls les JPEG, PNG ou WebP sont acceptés",
  fileTooLarge: "L’image doit rester sous 24 Mo",
  badPath: "Chemin de stockage invalide",
  missingStill: "Cliché manquant",
  missingRole: "Rôle manquant",
  invalidPacket: "Paquet d’appareil invalide",
  unauthorizedWorker: "Ouvrier non autorisé",
  nameLook: "Nommez le lieu",
  photoFailed: "Le portrait n’est pas arrivé.",
  jobFailed: "Le portrait n’est pas arrivé.",
  missingSource: "Source photo manquante",
  demoFilm: "Le film n’est pas encore branché.",
  genFailed: "Le portrait n’est pas arrivé.",
  genTimeout: "Le portrait prend plus de temps. Nouvelle tentative automatique.",
  noImage: "Le portrait n’est pas arrivé.",
  noVideo: "Le film n’est pas arrivé.",
  downloadFailed: "Impossible de récupérer le cliché.",
  noImageModel: "Aucun modèle image n’est ouvert sur cet espace Alibaba",
  noVideoModel: "Aucun modèle film n’est ouvert sur cet espace Alibaba",
  badKey: "Singapour a refusé la clé. Créez une clé dans l’espace Singapour.",
  alibabaFailed: "Le portrait n’est pas arrivé.",
  mailSubject: "Votre cliché Studio IA Tchad",
  mailBody: (url: string, imageUrl?: string) =>
    imageUrl
      ? `Votre cliché est prêt :\n${url}\n\nTélécharger l’image :\n${imageUrl}`
      : `Votre cliché est prêt :\n${url}\n\nOuvrez le lien pour le garder ou l’imprimer.`,
  sendStillFail: "Impossible d’envoyer le cliché",
  twoLetters: "Deux lettres au moins",
  eightChars: "Huit caractères au moins",
  invalidEmail: "Email invalide",
  mainBooth: "Booth principal",
} as const;
